"""
Cluster Model

Represents a face cluster generated by DBSCAN.
Each cluster belongs to one ProcessingJob and stores
its normalized centroid embedding.
"""

from __future__ import annotations

import uuid

from django.db import models
from django.contrib.postgres.fields import ArrayField

from .processing_job import ProcessingJob


class Cluster(models.Model):
    """
    Represents a cluster of similar faces.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    job = models.ForeignKey(
        ProcessingJob,
        on_delete=models.CASCADE,
        related_name="clusters",
        db_index=True,
    )

    cluster_number = models.PositiveIntegerField(
        help_text="Cluster label returned by DBSCAN"
    )

    centroid = ArrayField(
        base_field=models.FloatField(),
        size=512,
        null=True,
        blank=True,
        help_text="Normalized centroid embedding",
    )

    image_count = models.PositiveIntegerField(
        default=0
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        db_table = "clusters"

        ordering = [
            "cluster_number"
        ]

        indexes = [
            models.Index(fields=["job"]),
            models.Index(fields=["cluster_number"]),
            models.Index(fields=["created_at"]),
        ]

        constraints = [
            models.UniqueConstraint(
                fields=[
                    "job",
                    "cluster_number",
                ],
                name="unique_cluster_per_job",
            )
        ]

    # -------------------------------------------------------
    # Helper Methods
    # -------------------------------------------------------

    def update_image_count(self) -> None:
        """
        Update number of images inside cluster.
        """
        self.image_count = self.images.count()

        self.save(update_fields=["image_count"])

    @property
    def size(self) -> int:
        """
        Returns total images in cluster.
        """
        return self.image_count

    def __str__(self) -> str:
        return (
            f"Cluster {self.cluster_number} "
            f"({self.image_count} images)"
        )